### PR TITLE
Iterative algorithm

### PR DESCRIPTION
**Pull request by kgryte**
- Replace recursive algorithm with iterative algorithm.
- Based on same binary GCD algo.
- For safe ints, use bitwise ops. See about a 3x speed improvement on V8.
- For non-safe ints, use fallback iterative algo, which is ~10ns faster per iteration on V8 for small ints.
- Add tests for large values.
- Move int test to outer fcn.

### CODE REVIEW

**Comment by kgryte** [comment]
@Planeshifter what are your thoughts about possibly allowing a shortcut of sorts, where `gcd` accepts two `ints`, in addition to the current interface.

``` javascript
// Current:
gcd( [ 48, 18 ], function getValue(){} );

// Possible:
gcd( 48, 18 );
```

Part of the reason for the code duplication in `lcm` was to avoid creating a temporary `array` container and then the ensuing checks, when `lcm` already knows the inputs are positive integers. 

Other methods do allow for mixed input, e.g., `zip` which accepts either a single array of arrays or multiple arrays. 

Your thoughts?

**Comment by kgryte** [comment]
@Planeshifter updated the pull request to demo the polymorphic interface. Provided this interface, the `gcd` code in `lcm` is no longer needed.

**Comment by Planeshifter** [comment]
Sounds good to me, one question though: If  `gcd(48, 18)` was a possible input, I believe one would easily assume that `gcd(48, 18, 12)` was valid, too. I am not sure whether turning them into variadic functions is possible / desirable though because of the callback parameter. What do you think?

**Comment by kgryte** [comment]
Good point. I believe it is possible. Just adds a bit more code for parsing input args. Will update the pull request.

**Comment by kgryte** [comment]
@Planeshifter updated to support a variadic interface. Added comments to argument parsing. I believe it is more readable and maintainable than before.

How do things look to you?

**Comment by kgryte** [comment]
The one casualty is that, for object `arrays`, a temporary `array` is created to house accessed `array` values. Creating a temporary array is not the end of the world ==> not doing so leads to a bit more convoluted code where, at each iteration, whether the value is an integer and the sign has to be checked. Without the temp array, we also have the problem of whether to create a branched pathway based on the presence of a callback.

**Comment by Planeshifter** [comment]
For me, the code looks fine. One quick question, though: is there a specific reason why you loop through the elements of `arguments` to store them in `args` instead of using the standard `var args = Array.prototype.slice.apply(arguments)`?

**Comment by kgryte** [comment]
@Planeshifter yes :) See the following perf [comparison](http://jsperf.com/for-loop-versus-array-prototype-slice-apply). The behavior is consistent across browsers.

Almost anything with `arguments` is slow. For copying `arrays` and array-like `objects`, often better to do it by hand as opposed to `Array#slice()`. I have often found that the specification imposes certain requirements, which can slow down performance. These requirements generally relate to these methods needing to be "general" methods (e.g., can be applied to `arrays`, `objects`, `array`-like objects, `strings`, etc).

Re: why is `copy` not faster? Generally want to avoid passing the `arguments` object to any function. My understanding is that this can prevent the compiler from optimizing a `function`. I updated the perf comparison to demonstrate this fact.

**Pull request merged**
